spring.application.name=financial-parser

spring.datasource.url=jdbc:postgresql://localhost:5432/financial-parser
spring.datasource.username=postgres
spring.datasource.password=0102
spring.jpa.hibernate.ddl-auto=update